   version: '3.8'
   services:
     go-backend:
       build: ./backend/go-backend
       ports:
         - "8080:8080"
       depends_on:
         - log-analyzer
         - root-cause-predictor
         - knowledge-base
         - action-recommender
       volumes:
         - ./backend/go-backend/serviceAccountKey.json:/app/serviceAccountKey.json
         - ~/.kube/config:/root/.kube/config:ro
         - ~/.aws:/root/.aws:ro
       environment:
         - KUBECONFIG=/root/.kube/config
         - LOG_ANALYZER_URL=http://log-analyzer:8000/analyze
         - ROOT_CAUSE_PREDICTOR_URL=http://root-cause-predictor:8000/predict
         - KNOWLEDGE_BASE_URL=http://knowledge-base:8000/search
         - ACTION_RECOMMENDER_URL=http://action-recommender:8000/recommend
   
   

     log-analyzer:
       build:
         context: ./backend/python-services
         dockerfile: log_analyzer/Dockerfile
       ports:
         - "8001:8000"

     root-cause-predictor:
       build:
         context: ./backend/python-services
         dockerfile: root_cause_predictor/Dockerfile
       ports:
         - "8002:8000"

     knowledge-base:
       build:
         context: ./backend/python-services
         dockerfile: knowledge_base/Dockerfile
       ports:
         - "8003:8000"

     action-recommender:
       build:
         context: ./backend/python-services
         dockerfile: action_recommender/Dockerfile
       ports:
         - "8004:8000"

     incident-integrator:
       build:
         context: ./backend/python-services/incident_integrator
         dockerfile: Dockerfile
       ports:
         - "8005:8005"
       env_file:
         - backend/python-services/incident_integrator/.env

     k8s-log-scanner:
       build:
         context: ./backend/python-services
         dockerfile: k8s_log_scanner/Dockerfile
       ports:
         - "8006:8000"
       volumes:
         - ~/.kube:/root/.kube:ro  # Mount kubeconfig for cluster access
         - ~/.aws:/root/.aws:ro    # Mount AWS credentials
         - ~/.config/gcloud:/root/.config/gcloud:ro  # Mount GCP credentials
       environment:
         - KUBECONFIG=/root/.kube/config
         - AWS_PROFILE=aws-rnd-app

     frontend:
       build:
         context: ./frontend
       ports:
         - "3000:3000"
      #  volumes:
      #    - ./frontend:/app
       environment:
         - CHOKIDAR_USEPOLLING=true
       depends_on:
         - go-backend