apiVersion: v1
kind: ConfigMap
metadata:
  name: ira-config
  labels:
    app: incident-resolution-assistant
data:
  {{- range $key, $value := .Values.config.data }}
  {{ $key }}: "{{ $value }}"
  {{- end }} 