apiVersion: v1
kind: Service
metadata:
  name: go-backend
spec:
  type: ClusterIP
  selector:
    app: go-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http 