apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
spec:
  replicas: {{ .Values.goBackend.replicaCount }}
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
        - name: go-backend
          image: "{{ .Values.goBackend.image.repository }}:{{ .Values.goBackend.image.tag }}"
          env:
            {{- range $key, $value := .Values.goBackend.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.goBackend.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: go-backend-pvc
        {{- end }} 