{{- range $name, $svc := .Values.pythonServices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          env:
            {{- range $key, $value := $svc.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
          volumeMounts:
            {{- if $.Values.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
      volumes:
        {{- if $.Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ $name }}-pvc
        {{- end }}
{{- end }} 