{{- range $name, $svc := .Values.pythonServices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
{{- end }} 