apiVersion: v1
kind: Secret
metadata:
  name: ira-secret
  labels:
    app: incident-resolution-assistant
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }} 